// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// col_first
NumericVector col_first(NumericMatrix x, int allow_na);
RcppExport SEXP _hydrotoolbox_col_first(SEXP xSEXP, SEXP allow_naSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type allow_na(allow_naSEXP);
    rcpp_result_gen = Rcpp::wrap(col_first(x, allow_na));
    return rcpp_result_gen;
END_RCPP
}
// col_last
NumericVector col_last(NumericMatrix x, int allow_na);
RcppExport SEXP _hydrotoolbox_col_last(SEXP xSEXP, SEXP allow_naSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type allow_na(allow_naSEXP);
    rcpp_result_gen = Rcpp::wrap(col_last(x, allow_na));
    return rcpp_result_gen;
END_RCPP
}
// col_max
NumericVector col_max(NumericMatrix x, int allow_na);
RcppExport SEXP _hydrotoolbox_col_max(SEXP xSEXP, SEXP allow_naSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type allow_na(allow_naSEXP);
    rcpp_result_gen = Rcpp::wrap(col_max(x, allow_na));
    return rcpp_result_gen;
END_RCPP
}
// col_mean
NumericVector col_mean(NumericMatrix x, int allow_na);
RcppExport SEXP _hydrotoolbox_col_mean(SEXP xSEXP, SEXP allow_naSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type allow_na(allow_naSEXP);
    rcpp_result_gen = Rcpp::wrap(col_mean(x, allow_na));
    return rcpp_result_gen;
END_RCPP
}
// col_min
NumericVector col_min(NumericMatrix x, int allow_na);
RcppExport SEXP _hydrotoolbox_col_min(SEXP xSEXP, SEXP allow_naSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type allow_na(allow_naSEXP);
    rcpp_result_gen = Rcpp::wrap(col_min(x, allow_na));
    return rcpp_result_gen;
END_RCPP
}
// col_sd
NumericVector col_sd(NumericMatrix x, int allow_na);
RcppExport SEXP _hydrotoolbox_col_sd(SEXP xSEXP, SEXP allow_naSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type allow_na(allow_naSEXP);
    rcpp_result_gen = Rcpp::wrap(col_sd(x, allow_na));
    return rcpp_result_gen;
END_RCPP
}
// col_stats_cpp
NumericVector col_stats_cpp(NumericMatrix x, std::string stats, double allow_na);
RcppExport SEXP _hydrotoolbox_col_stats_cpp(SEXP xSEXP, SEXP statsSEXP, SEXP allow_naSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type stats(statsSEXP);
    Rcpp::traits::input_parameter< double >::type allow_na(allow_naSEXP);
    rcpp_result_gen = Rcpp::wrap(col_stats_cpp(x, stats, allow_na));
    return rcpp_result_gen;
END_RCPP
}
// col_sum
NumericVector col_sum(NumericMatrix x, int allow_na);
RcppExport SEXP _hydrotoolbox_col_sum(SEXP xSEXP, SEXP allow_naSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type allow_na(allow_naSEXP);
    rcpp_result_gen = Rcpp::wrap(col_sum(x, allow_na));
    return rcpp_result_gen;
END_RCPP
}
// cumsum_matrix
NumericMatrix cumsum_matrix(NumericMatrix x);
RcppExport SEXP _hydrotoolbox_cumsum_matrix(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cumsum_matrix(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hydrotoolbox_col_first", (DL_FUNC) &_hydrotoolbox_col_first, 2},
    {"_hydrotoolbox_col_last", (DL_FUNC) &_hydrotoolbox_col_last, 2},
    {"_hydrotoolbox_col_max", (DL_FUNC) &_hydrotoolbox_col_max, 2},
    {"_hydrotoolbox_col_mean", (DL_FUNC) &_hydrotoolbox_col_mean, 2},
    {"_hydrotoolbox_col_min", (DL_FUNC) &_hydrotoolbox_col_min, 2},
    {"_hydrotoolbox_col_sd", (DL_FUNC) &_hydrotoolbox_col_sd, 2},
    {"_hydrotoolbox_col_stats_cpp", (DL_FUNC) &_hydrotoolbox_col_stats_cpp, 3},
    {"_hydrotoolbox_col_sum", (DL_FUNC) &_hydrotoolbox_col_sum, 2},
    {"_hydrotoolbox_cumsum_matrix", (DL_FUNC) &_hydrotoolbox_cumsum_matrix, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_hydrotoolbox(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
