# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

col_first <- function(x, allow_na) {
    .Call(`_hydrotoolbox_col_first`, x, allow_na)
}

col_last <- function(x, allow_na) {
    .Call(`_hydrotoolbox_col_last`, x, allow_na)
}

col_max <- function(x, allow_na) {
    .Call(`_hydrotoolbox_col_max`, x, allow_na)
}

col_mean <- function(x, allow_na) {
    .Call(`_hydrotoolbox_col_mean`, x, allow_na)
}

col_min <- function(x, allow_na) {
    .Call(`_hydrotoolbox_col_min`, x, allow_na)
}

col_sd <- function(x, allow_na) {
    .Call(`_hydrotoolbox_col_sd`, x, allow_na)
}

col_stats_cpp <- function(x, stats, allow_na) {
    .Call(`_hydrotoolbox_col_stats_cpp`, x, stats, allow_na)
}

col_sum <- function(x, allow_na) {
    .Call(`_hydrotoolbox_col_sum`, x, allow_na)
}

cumsum_matrix <- function(x) {
    .Call(`_hydrotoolbox_cumsum_matrix`, x)
}

